services:
  frontend:
  build:
    context: ./frontend
    dockerfile: DOCKERFILE
  container_name: frontend_web
  hostname: frontend  # Añadir hostname explícito
  networks:
    backend_network:
      aliases:
        - frontend
  ports:
    - "5173:5173"
  restart: unless-stopped
  healthcheck:
    test:
      [
        "CMD",
        "wget",
        "--quiet",
        "--tries=1",
        "--spider",
        "http://localhost:5173",
      ]
    interval: 10s
    timeout: 5s
    retries: 3

# Definición de redes
networks:
  backend_network:
    driver: bridge
    # Remover ipam para que Podman asigne automáticamente

